apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspwebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspwebapp
  template:
    metadata:
      labels:
        app: aspwebapp
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: aspwebapp
        image: myrg1234.azurecr.io/webappsdk6:latest
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
   
